### PR TITLE
Create a bbox GeoJSON FeatureCollection so see which tiles get warmed

### PR DESCRIPTION
**Pull request by tordans**
Drop the .geojson in https://play.placemark.io/ to have a quick look.

### CODE REVIEW

**Comment by rush42** [comment]
Maybe it would be useful to parameterize the cache warming with a bbox instead of a viewport and a map center ? That way it would be clearer for which area we want warm the cache...

**Comment by rush42** [comment]
While I was inspecting the server logs, I saw that the counter of `warm-cash` overshoots the limit. This is due to the exponential grow in tile size described by 4^zoom. To compute the actual boundary we need to compute a [geometric series](https://en.wikipedia.org/wiki/Geometric_series) but even that one might differ by a few tiles due to boundary effects.

**Comment by tordans** [comment]
Merged with something else … closing here.

**Comment by elsueno** [comment]
Es gibt jetzt visualizeLog.ts das aus einem Logfile ein .geojson der heruntergeladenen Tiles generiert:
```
$ cd atlas-geo/warm-cache
$ source init-commands.sh
$ warm
2024-04-04T09:59:47 ℹ Using config ./config.json
...
$ visualize -h
Usage: visulizeLog [options] <logfile> <geojson>
Creates a <geojson> from <logfile> visualizing screen size, requests and responses
...
$ visualize
Saved data to geojson/warm.geojson.
```

**Pull request closed without merging**
